### ISSUE TITLE
Add screenshot of the app/tool or GIF of it working in the main README

### ISSUE THREAD

**Issue by ArielMAJ** [DSoftofficial/Tilder#40]
Seeing how it works might make people more interested in using/contributing.

**Comment by Dhrubajyo** [comment]
By tommorow, we will do

**Comment by Dhrubajyo** [comment]
Can you contribute abour Monaco-editor here? https://github.com/DSoftofficial/Tilder/issues/30

**Comment by dhrubajyotifounderofDSoft** [comment]
Done in the latest commit 54e7b64.
